apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: {{ name }}
  namespace: bidrag
  labels:
    team: bidrag
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
    inbound:
      rules:
      {{#each azureAccessInbound}}
         - application: {{this.application}}
           namespace: {{this.namespace}}
           cluster: {{this.cluster}}
      {{/each}}
    outbound:
      external:
        - host: {{ azure.unsecure.kodeverk_url }}
  image: {{ image }}
  liveness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /actuator/health
    initialDelay: 20
    timeout: 1
  prometheus:
    enabled: true
    path: /actuator/prometheus
  secureLogs:
    enabled: true
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 1024Mi
    replicas:
      cpuThresholdPercentage: 80
      max: 4
      min: {{ spec.replicas.min }}
  ingresses:
  {{#each ingresses as |url|}}
     - {{url}}
  {{/each}}
  env:
    - name: KODEVERK_URL
      value: https://{{ azure.unsecure.kodeverk_url }}
  {{#each env}}
    - name: {{this.name}}
      value: "{{this.value}}"
  {{/each}}
