name: bidrag-inntekt
ingresses:
  - https://bidrag-inntekt.intern.nav.no
spec:
  replicas:
    min: 2
azureAccessInbound:
  - application: bidrag-behandling-feature
    namespace: bidrag
    cluster: prod-gcp
  - application: bidrag-ui
    namespace: bidrag
    cluster: prod-fss
