name: bidrag-inntekt
ingresses:
  - https://bidrag-inntekt.intern.nav.no
spec:
  replicas:
    min: 1
azure:
  unsecure:
    kodeverk_url: kodeverk.prod-fss-pub.nais.io
azureAccessInbound:
  - application: bidrag-behandling
    namespace: bidrag
    cluster: prod-gcp
  - application: bidrag-ui
    namespace: bidrag
    cluster: prod-fss
