####################################################################
#
# Profiles: All
#
####################################################################
springdoc:
  swagger-ui:
    path: /
  packages-to-scan: no.nav.bidrag.inntekt.controller

management:
  endpoints:
    web:
      exposure:
        include: "*"

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

---
spring:
  config.activate.on-profile: local
KODEVERK_URL: https://kodeverk.dev-fss-pub.nais.io
server:
  port: 1717