####################################################################
#
# Profiles: All
#
####################################################################
springdoc:
  swagger-ui:
    path: /

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

no.nav.security.jwt:
  issuer:
    aad:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

