name: Deploy to dev
on:
  pull_request:
    types: [ ready_for_review, opened, synchronize ]
  push:
    branches:
      - 'main'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-deploy:
    name: "Build and deploy to main"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/pr.yaml@main
    secrets: inherit