name: Deploy to dev
on:
  pull_request:
    types: [ ready_for_review, opened, synchronize ]
  push:
    branches:
      - 'main'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-deploy:
    name: "Build and deploy to main"
    permissions:
      contents: "read"
      id-token: "write"
    uses: navikt/bidrag-workflow/.github/workflows/deploy.yaml@main
    secrets: inherit
    with:
      nais_variabler_filnavn: main.yaml

  automerge_dependabot:
    name: "Automerge dependabot updates"
    runs-on: ubuntu-latest
    needs: build-deploy
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}